name = "sparkfun-redv"
target = "riscv32imac-unknown-none-elf"
board = "redv"
stacksize = 1024

[kernel]
path = "."
name = "sparkfun-redv"
requires = {flash = 32768, ram = 4096}
features = ["semihosting"]

[supervisor]
notification = 1

# QSPI-0 flash (32MB), skipping the first 64k bootloader
[outputs.flash]
address = 0x20010000
size = 0x1FF0000
read = true
execute = true

# RAM sections are currently mapped into DTIM, a small but fast SRAM.
[outputs.ram]
address = 0x80000000
size = 16384
read = true
write = true
execute = false  # let's assume XN until proven otherwise

[tasks.jefe]
path = "../../task/jefe"
name = "task-jefe"
priority = 0
requires = {flash = 16384, ram = 2048}
start = true
features = ["semihosting-riscv"]
stacksize = 1536

[tasks.pong]
path = "../../task/pong"
name = "task-pong"
priority = 3
requires = {flash = 8192, ram = 1024}
start = true
#task-slots = ["user_leds"]

[tasks.ping]
path = "../../task/ping"
name = "task-ping"
priority = 3
requires = {flash = 8192, ram = 1024}
stacksize = 512
start = true
task-slots = [{peer = "pong"}]

[tasks.idle]
path = "../../task/idle"
name = "task-idle"
priority = 5
requires = {flash = 256, ram = 256}
stacksize = 256
start = true
