[package]
name = "drv-stm32g0-rcc"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
stm32g0 = { git = "https://github.com/stm32-rs/stm32-rs-nightlies", branch = "master", default-features = false }
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
g031 = ["stm32g0/stm32g031"]
g070 = ["stm32g0/stm32g070"]
g0b1 = ["stm32g0/stm32g0b1"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32g0-rcc"
test = false
bench = false
